### ISSUE TITLE
Error establishing a database connection w/ Docker

### ISSUE THREAD

**Issue by moimikey** [wordplate/wordplate#205]
hi,

is there something extra that needs to happen in order to dockerize wordplate? i can't seem to avoid `Error establishing a database connection`

docker-compose.yml:
```yml
version: "3"
services:
  web:
    image: richarvey/nginx-php-fpm:latest
    container_name: web
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./public:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    links:
      - mysql
      - redis
    environment:
      - HIDE_NGINX_HEADERS=1
      - ERRORS=1
      - PHP_ERRORS_STDERR=1
      - DOMAIN=vcap.me
      - SKIP_COMPOSER=1
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "1234:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    restart: always

  mysql:
    image: mariadb:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    restart: always

  redis:
    image: redis:latest

volumes:
  mariadb_data:

networks:
  default:

```
